In [22]:
import pandas as pd
import numpy as np

In [23]:
df= pd.read_excel('COVID-19.xlsx')
df

,Sno,age,gender,body temperature,Dry Cough,sour throat,weakness,breathing problem,drowsiness,pain in chest,...,diabetes,heart disease,lung disease,stroke or reduced immunity,symptoms progressed,high blood pressue,kidney disease,change in appetide,Loss of sense of smell,Corona result
0,1,20,1,98.6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,19,1,99.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,55,0,102.0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,1,0,1
3,4,40,0,100.0,0,0,0,0,1,1,...,1,0,0,0,1,1,0,1,0,2
4,5,33,1,99.2,0,1,0,1,0,0,...,0,0,1,1,1,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,123,37,1,102.0,1,1,1,1,0,0,...,0,0,0,0,1,0,0,1,0,0
123,124,35,0,100.0,0,0,0,0,1,1,...,1,0,0,0,0,1,0,1,0,1
124,125,22,1,99.2,0,0,0,1,0,0,...,0,0,0,1,1,0,0,0,1,1
125,126,29,0,102.0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,1,1,0
126,127,38,0,101.0,1,1,0,1,1,1,...,1,0,0,0,1,1,0,0,0,2

In [24]:
from sklearn.naive_bayes import BernoulliNB

In [25]:
Y = df['Corona result']

for i in range (len(Y)):
  if(Y[i] == 2):
    Y[i] = 1
Y

<ipython-input-25-3393514c843d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y[i] = 1

0      0
1      0
2      1
3      1
4      1
      ..
122    0
123    1
124    1
125    0
126    1
Name: Corona result, Length: 127, dtype: int64

In [26]:
X = df.drop(['Corona result', 'Sno'], axis = 1)
X

,age,gender,body temperature,Dry Cough,sour throat,weakness,breathing problem,drowsiness,pain in chest,travel history to infected countries,diabetes,heart disease,lung disease,stroke or reduced immunity,symptoms progressed,high blood pressue,kidney disease,change in appetide,Loss of sense of smell
0,20,1,98.6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19,1,99.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,55,0,102.0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0
3,40,0,100.0,0,0,0,0,1,1,1,1,0,0,0,1,1,0,1,0
4,33,1,99.2,0,1,0,1,0,0,1,0,0,1,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,37,1,102.0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0
123,35,0,100.0,0,0,0,0,1,1,1,1,0,0,0,0,1,0,1,0
124,22,1,99.2,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1
125,29,0,102.0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1
126,38,0,101.0,1,1,0,1,1,1,1,1,0,0,0,1,1,0,0,0

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X,Y, test_size=0.2)

In [28]:
clf = BernoulliNB()
>>> clf.fit(X_train, y_train)

BernoulliNB()

In [29]:
y_pred= clf.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.8076923076923077

In [31]:
import pickle

In [32]:
pickle.dump(clf, open('covidmodel', 'wb'))

In [ ]:
newMethod = pkl.load(open('covidmodel', 'rb'))
testList = [18,0,97,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
newMethod.predict(testList)